window.SHEEP_ONE=[
"Le contraire de chaud : ___",
"Le contraire de grand : ___",
"Le contraire de rapide : ___",
"Le contraire de jeune : ___",
"Le contraire de propre : ___",
"Le contraire de plein : ___",
"Le contraire de vrai : ___",
"Le contraire de gauche : ___",
"Le contraire de jour : ___",
"Le contraire de monter : ___",
"Une vache donne du ___",
"Une poule pond des ___",
"Une abeille fait du ___",
"Un mouton donne de la ___",
"Un chien remue la ___",
"Un chat chasse les ___",
"Un panda mange du ___",
"Un poisson vit dans l’___",
"Un oiseau a des ___",
"Un serpent n’a pas de ___",
"Un éléphant a une ___",
"Une girafe a un long ___",
"Un kangourou a une ___",
"Une araignée a huit ___",
"Un escargot porte sa ___",
"Un lion a une ___",
"Un vélo a deux ___",
"Une voiture a quatre ___",
"Un dé classique a six ___",
"Une semaine a sept ___",
"Une année a douze ___",
"Une heure a soixante ___",
"Un triangle a trois ___",
"Un carré a quatre ___",
"Une main a cinq ___",
"Une douzaine, c’est ___",
"Quand il pleut, on prend un ___",
"Quand il neige, on fait un bonhomme de ___",
"Quand on se lave les dents, on utilise une ___",
"Pour téléphoner, on utilise un ___",
"Pour regarder un film, on peut aller au ___",
"Pour envoyer une lettre, il faut un ___",
"Pour couper du papier, on utilise des ___",
"Pour effacer du crayon, on utilise une ___",
"Pour se protéger du soleil, on met des ___",
"Pour dormir, on ferme les ___",
"Pour entendre, on utilise ses ___",
"Pour sentir, on utilise son ___",
"Pour applaudir, on utilise ses ___",
"Pour voir dans le noir, on utilise une ___",
"Le matin, on prend le petit-___",
"À Noël, on décore un ___",
"À Pâques, on cherche des ___",
"À la plage, on construit un château de ___",
"Au cinéma, on mange souvent du ___",
"Au restaurant, on demande l’___",
"Dans une voiture, on attache sa ___",
"Dans une piscine, on met un maillot de ___",
"Dans un lit, on pose sa tête sur un ___",
"Dans un jardin, on peut tondre la ___",
"Dans un frigo, il fait ___",
"Un animal qui fait « miaou » : ___",
"Un animal qui fait « ouaf » : ___",
"Un animal à trompe : ___",
"Un animal avec un très long cou : ___",
"Un animal qui a une crinière : ___",
"Un animal qui donne de la laine : ___",
"Un animal qui vit dans une ruche : ___",
"Un animal qui porte une carapace et avance très lentement : ___",
"Un animal qui a huit pattes : ___",
"Un animal qui porte ses petits dans une poche : ___",
"Un fruit qu’on presse souvent au petit-déjeuner : ___",
"Un légume qui fait pleurer quand on le coupe : ___",
"Un condiment rouge qu’on met sur les frites : ___",
"Un condiment jaune qu’on met sur un hot-dog : ___",
"Un aliment qu’on met dans un grille-pain : ___",
"Une boisson chaude faite avec des grains moulus : ___",
"Le repas du matin : ___",
"Un aliment fabriqué avec du lait et qu’on met sur une pizza : ___",
"La capitale de la France : ___",
"La monnaie utilisée en France : ___",
"Une langue parlée en Espagne : ___",
"La planète où vivent les humains : ___",
"La planète rouge : ___",
"Le pays du Soleil-Levant : ___",
"La ville de la Tour Eiffel : ___",
"Le sport de Roland-Garros : ___",
"Le sport du Tour de France : ___",
"Le sport où l’on marque des paniers : ___",
"Le sport où l’on marque des buts avec les pieds : ___",
"Un objet pour gommer : ___",
"Un objet pour couper du papier : ___",
"Un objet pour ouvrir une porte : ___",
"Un objet qui donne l’heure au poignet : ___",
"Un objet qu’on ouvre quand il pleut : ___",
"Un objet qu’on met sous sa tête pour dormir : ___",
"Un objet qui sert à se coiffer : ___",
"Un objet pour se regarder : ___",
"Un objet pour prendre une photo : ___",
"Un objet qui sert à balayer le sol : ___",
"À Noël, le Père ___",
"Blanche-___",
"Le Petit Chaperon ___",
"Les trois petits ___",
"La Belle et la ___",
"Tom et ___",
"Astérix et ___",
"Tic et ___",
"Pierre, feuille, ___",
"Sel et ___",
"À tes ___ !",
"Le bon, la brute et le ___",
"Ni oui ni ___",
"Mickey et ___",
"Mario et ___",
"Roméo et ___",
"Bonnie et ___",
"Starsky et ___",
"Laurel et ___",
"Harry Potter est un ___",
"Cendrillon perd une ___",
"Le plombier moustachu de Nintendo : ___",
"Le Pokémon jaune le plus connu : ___",
"Le sorcier à lunettes avec une cicatrice : ___",
"Le super-héros qui grimpe aux murs : ___",
"Le héros gaulois ami d’Obélix : ___",
"Le cowboy de Toy Story : ___",
"Le bonhomme de neige de La Reine des Neiges : ___",
"Le frère de Mario : ___",
"On mange la soupe avec une ___",
"On coupe la viande avec un ___",
"On boit dans un ___",
"On dort dans un ___",
"On s’assoit sur une ___",
"On ouvre une conserve avec un ouvre-___",
"On sèche ses cheveux avec un sèche-___",
"On fait cuire un gâteau dans un ___",
"On nettoie ses dents avec une brosse à ___",
"On lave ses cheveux avec du ___",
"À la boulangerie, on achète du ___",
"Chez le coiffeur, on se fait couper les ___",
"Chez le dentiste, on ouvre la ___",
"À la piscine, on nage dans l’___",
"À la gare, on prend le ___",
"À l’aéroport, on prend l’___",
"À la poste, on envoie une ___",
"À la pharmacie, on achète des ___",
"Au zoo, on voit des ___",
"Au stade, on regarde un ___",
"Le roi des animaux : ___",
"Le meilleur ami de l’homme : ___",
"La langue de Shakespeare : ___",
"La fête des amoureux : ___",
"La ville lumière : ___",
"Le métal précieux jaune : ___",
"Le satellite naturel de la Terre : ___",
"L’étoile qui éclaire la Terre : ___",
"L’eau solide : ___",
"Le jour après lundi : ___"
];
