window.SHEEP_THREE=[
"La chose la plus importante dans un couple : ___",
"La chose la plus importante dans une amitié : ___",
"La chose la plus importante pour réussir : ___",
"La chose la plus importante pour être heureux : ___",
"La qualité la plus importante chez un parent : ___",
"La qualité la plus importante chez un patron : ___",
"Le défaut le plus difficile à supporter : ___",
"Le pire défaut chez un colocataire : ___",
"Le trait de caractère le plus attirant : ___",
"Le trait de caractère le plus énervant : ___",
"La première chose à acheter si vous gagnez au loto : ___",
"La première chose à faire si vous devenez riche : ___",
"La première chose à sauver si votre maison brûle : ___",
"La première chose à faire si vous pouvez arrêter le temps : ___",
"La première chose à faire si vous êtes invisible une heure : ___",
"La première chose à faire avec une journée entièrement libre : ___",
"La première chose à faire sans internet pendant une semaine : ___",
"La première chose à acheter avec 10 000 € : ___",
"Le meilleur super-pouvoir dans la vraie vie : ___",
"Le pire super-pouvoir à avoir : ___",
"Le pouvoir magique le plus utile au quotidien : ___",
"Le personnage de fiction à inviter à dîner : ___",
"Le personnage de fiction avec qui partir en vacances : ___",
"Le personnage de fiction à éviter comme voisin : ___",
"Le personnage historique à rencontrer : ___",
"La célébrité avec qui boire un verre : ___",
"La célébrité qui ferait un bon professeur : ___",
"La célébrité qui ferait un mauvais babysitter : ___",
"Le pays à visiter une fois dans sa vie : ___",
"Le pays où vous pourriez vivre : ___",
"Le pays où vous ne voudriez pas vivre : ___",
"La ville parfaite pour commencer une nouvelle vie : ___",
"La ville parfaite pour un week-end fou : ___",
"Le meilleur endroit pour vivre : ___",
"Le pire endroit pour être bloqué 24 heures : ___",
"Le meilleur endroit pour cacher un trésor : ___",
"Le meilleur endroit pour faire une demande en mariage : ___",
"Le pire endroit pour rompre : ___",
"Le meilleur âge de la vie : ___",
"L’âge auquel on devient vraiment adulte : ___",
"L’âge idéal pour arrêter de travailler : ___",
"À partir de quel âge est-on vieux ? ___ ans",
"À partir de combien de degrés fait-il froid ? ___ °C",
"Combien faut-il gagner par mois pour être riche ? ___ €",
"Combien de minutes peut-on raisonnablement être en retard ? ___",
"Combien de jours de vacances faudrait-il par an ? ___",
"Combien d’heures de sommeil sont idéales ? ___",
"Combien faut-il mettre dans une enveloppe de mariage ? ___ €",
"Le plus grand luxe du quotidien : ___",
"Le luxe le plus inutile : ___",
"La dépense qu’on regrette le plus facilement : ___",
"La meilleure façon de dépenser 1 000 € : ___",
"La pire façon de dépenser 1 000 € : ___",
"La chose pour laquelle ça vaut le coup de payer cher : ___",
"La chose qui devrait être gratuite : ___",
"La chose qu’on devrait interdire : ___",
"Une règle sociale absurde : ___",
"Une chose trop chère pour ce que c’est : ___",
"Une chose que tout le monde devrait apprendre : ___",
"Une chose qu’on devrait apprendre à l’école : ___",
"Une chose qu’on apprend trop tard dans la vie : ___",
"Le meilleur conseil à donner à un enfant : ___",
"Le pire conseil qu’on puisse donner : ___",
"La chose la plus difficile à pardonner : ___",
"La chose la plus difficile à partager : ___",
"La chose la plus difficile à avouer : ___",
"La chose la plus difficile à jeter : ___",
"Une chose qu’on regrette souvent de ne pas avoir faite : ___",
"Le pire métier au monde : ___",
"Le meilleur métier pour avoir du temps libre : ___",
"Le meilleur métier pour devenir riche : ___",
"Le métier le plus sous-estimé : ___",
"Le métier le plus surestimé : ___",
"Le métier le plus impressionnant : ___",
"Le métier où vous ne tiendriez pas une journée : ___",
"Le métier qu’on devrait payer beaucoup plus : ___",
"Le métier qui fait le plus rêver les enfants : ___",
"La meilleure invention de tous les temps : ___",
"La pire invention moderne : ___",
"L’invention qu’il faudrait créer demain : ___",
"L’invention dont on pourrait se passer : ___",
"L’application qui prend trop de place dans nos vies : ___",
"Le réseau social le plus toxique : ___",
"Le réseau social le plus utile : ___",
"La meilleure chose qu’internet ait apportée : ___",
"La pire chose qu’internet ait apportée : ___",
"L’objet moderne dont vous pourriez le moins vous passer : ___",
"Le meilleur film de tous les temps : ___",
"Le film le plus surcoté : ___",
"Le film qu’on peut revoir dix fois : ___",
"La série qu’on recommanderait à tout le monde : ___",
"La série la plus surcotée : ___",
"La chanson parfaite pour finir une soirée : ___",
"La chanson qu’on ne veut plus jamais entendre : ___",
"Le chanteur ou la chanteuse le plus surcoté : ___",
"Le meilleur groupe de tous les temps : ___",
"Le meilleur rappeur français : ___",
"Le meilleur acteur français : ___",
"La meilleure actrice française : ___",
"Le meilleur joueur de football français : ___",
"Le sportif français le plus impressionnant : ___",
"Le dessin animé que les adultes aiment autant que les enfants : ___",
"Le meilleur plat du monde : ___",
"Le plat français le plus surcoté : ___",
"Le plat qu’on pourrait manger toute sa vie : ___",
"L’aliment qu’on supprimerait du monde : ___",
"L’aliment le plus addictif : ___",
"Le pire ingrédient sur une pizza : ___",
"Le meilleur repas de lendemain de soirée : ___",
"Le meilleur petit-déjeuner possible : ___",
"Le meilleur accompagnement pour des frites : ___",
"Le truc qu’on devrait toujours avoir dans son frigo : ___",
"Le truc le plus bizarre à manger au petit-déjeuner : ___",
"Le plat qu’on ne commanderait jamais au premier rendez-vous : ___",
"Le pire cadeau d’anniversaire : ___",
"Le meilleur cadeau qu’on puisse recevoir : ___",
"Le cadeau qu’on offre quand on n’a aucune idée : ___",
"La meilleure excuse pour annuler un rendez-vous : ___",
"La pire excuse pour être en retard : ___",
"La phrase qu’on ne veut pas entendre dans un avion : ___",
"La phrase qu’on ne veut pas entendre chez le médecin : ___",
"La phrase qu’on ne veut pas entendre au restaurant : ___",
"La phrase qu’on ne veut pas entendre pendant un mariage : ___",
"La pire chose à oublier avant un voyage : ___",
"La chose la plus gênante à faire en public : ___",
"La chose la plus drôle à voir dans la rue : ___",
"La chose la plus bizarre à voir chez un voisin : ___",
"La chose la plus gênante à trouver dans l’historique de quelqu’un : ___",
"La pire personne à croiser quand on sèche le travail : ___",
"Le pire message à envoyer à la mauvaise personne : ___",
"Le pire endroit pour avoir une envie pressante : ___",
"Le pire moment pour que son téléphone sonne : ___",
"Le truc le plus suspect à avoir dans son coffre : ___",
"Le vêtement le plus gênant à porter à un mariage : ___",
"Qui ici survivrait le plus longtemps dans Koh-Lanta ?",
"Qui ici dépenserait le plus vite un million d’euros ?",
"Qui ici serait le meilleur candidat à un jeu télé ?",
"Qui ici oublierait son propre anniversaire ?",
"Qui ici serait le plus capable de vivre sans téléphone ?",
"Qui ici serait le pire président ?",
"Qui ici arriverait le plus souvent en retard à son propre mariage ?",
"Qui ici pourrait devenir célèbre par accident ?",
"Qui ici tiendrait le moins longtemps sans parler ?",
"Qui ici serait le meilleur espion ?",
"Qui ici serait le plus mauvais menteur ?",
"Qui ici partirait en vacances sans rien préparer ?",
"Qui ici survivrait le moins longtemps dans un film d’horreur ?",
"Qui ici serait le meilleur pour négocier un prix ?",
"Qui ici serait le plus susceptible de rire pendant un moment sérieux ?",
"Pain au chocolat ou chocolatine ?",
"Mer ou montagne ?",
"Chien ou chat ?",
"Matin ou soir ?",
"Douche ou bain ?",
"Été ou hiver ?",
"Sucré ou salé ?",
"Ville ou campagne ?",
"Film ou série ?",
"Appel ou SMS ?",
"Restaurant ou livraison ?",
"Vacances organisées ou improvisées ?",
"Argent ou temps libre ?",
"Être très beau ou très intelligent ?",
"Être trop grand ou trop petit ?",
"Ne plus jamais utiliser internet ou ne plus jamais regarder la télé ?",
"Toujours arriver 20 minutes trop tôt ou 10 minutes trop tard ?",
"Savoir voler ou être invisible ?",
"Connaître son avenir ou pouvoir changer son passé ?",
"Pouvoir lire dans les pensées ou voir l’avenir ?",
"Ne plus jamais manger sucré ou ne plus jamais manger salé ?",
"Vivre sans musique ou vivre sans films ?",
"Être célèbre ou être très riche sans être connu ?",
"Avoir toujours trop chaud ou toujours trop froid ?",
"Partir un an autour du monde ou acheter la maison de ses rêves ?",
"Si je dis « richesse », vous dites : ___",
"Si je dis « vacances de rêve », vous dites : ___",
"Si je dis « succès », vous dites : ___",
"Si je dis « famille », vous dites : ___",
"Si je dis « liberté », vous dites : ___",
"Si je dis « luxe », vous dites : ___",
"Si je dis « peur », vous dites : ___",
"Si je dis « bonheur », vous dites : ___",
"La pire chaîne de télé : ___",
"La matière la moins utile à l’école : ___",
"Le prix normal d’un kebab : ___ €",
"Le prix normal d’un jambon-beurre : ___ €",
"Le meilleur mois de l’année : ___",
"Le pire mois de l’année : ___",
"Le meilleur jour pour ne rien faire : ___",
"La meilleure heure pour se lever le week-end : ___",
"Le temps maximum acceptable aux toilettes : ___ minutes",
"Le nombre idéal d’enfants : ___",
"Le nombre idéal de jours pour partir en vacances : ___",
"Le pourboire idéal au restaurant : ___ €",
"La meilleure chanteuse francophone : ___",
"Le Français le plus connu dans le monde : ___",
"La personnalité française la plus drôle : ___",
"Le plus grand chanteur français : ___",
"La personnalité qu’on inviterait en premier à une soirée : ___"
];
