window.SHEEP_TWO=[
"Un synonyme mignon de zizi : ___",
"C’est tabou : ___",
"Un truc de beauf : ___",
"Un loisir de riche : ___",
"Un loisir de retraité : ___",
"Un truc qu’on associe aux ados : ___",
"Un truc qu’on associe aux parents : ___",
"Un truc qu’on associe aux vacances au camping : ___",
"Un truc qu’on associe à une soirée étudiante : ___",
"Un truc qu’on associe à un mariage : ___",
"Le plus grand chanteur français : ___",
"La meilleure chanteuse francophone : ___",
"Le meilleur acteur français : ___",
"La meilleure actrice française : ___",
"Le meilleur joueur de foot français : ___",
"Le meilleur humoriste français : ___",
"La pire chaîne de télé : ___",
"Le film français que tout le monde connaît : ___",
"La série française que tout le monde connaît : ___",
"La chanson française que tout le monde connaît : ___",
"Le dessin animé qu’on regardait enfant : ___",
"Un film avec Leonardo DiCaprio : ___",
"Un film avec Tom Cruise : ___",
"Un film avec Brad Pitt : ___",
"Un film avec Jean Dujardin : ___",
"Un film avec Louis de Funès : ___",
"Un personnage de Harry Potter : ___",
"Un personnage de Star Wars : ___",
"Un personnage de Disney : ___",
"Un personnage de Mario : ___",
"Un Pokémon connu : ___",
"Si je dis « Francis », vous dites : ___",
"Si je dis « Michel », vous dites : ___",
"Si je dis « Jacques », vous dites : ___",
"Si je dis « Jackie », vous dites : ___",
"Si je dis « Toulouse », vous dites : ___",
"Si je dis « gland », vous dites : ___",
"Si je dis « arbre », vous dites : ___",
"Si je dis « rouge », vous dites : ___",
"Si je dis « café », vous dites : ___",
"Si je dis « voiture », vous dites : ___",
"Si je dis « amour », vous dites : ___",
"Le panda est-il un ours ?",
"Manger un brownie parfum caca ou un caca parfum brownie ?",
"Qui ici est le plus maladroit ?",
"Le prix normal d’un kebab : ___ €",
"Le prix normal d’un café en terrasse : ___ €",
"Le prix normal d’une pizza : ___ €",
"Le prix normal d’un menu fast-food : ___ €",
"Le prix normal d’une baguette : ___ €",
"Le prix normal d’un cadeau d’anniversaire : ___ €",
"Le prix normal d’une nuit d’hôtel : ___ €",
"Le prix normal d’un coiffeur homme : ___ €",
"Le prix normal d’un coiffeur femme : ___ €",
"Le prix normal d’un plein d’essence : ___ €",
"La matière la moins utile à l’école : ___",
"Une matière qu’on redoute à l’école : ___",
"Une matière où on peut facilement s’endormir : ___",
"Une matière qui fait souvent peur aux élèves : ___",
"Une matière qu’on aimerait supprimer : ___",
"Une matière qu’on devrait ajouter à l’école : ___",
"Le pire jour pour avoir cours : ___",
"Le meilleur moment de la journée au lycée : ___",
"Le truc le plus pénible à l’école : ___",
"Le truc qu’on oublie le plus souvent dans son cartable : ___",
"Un métier qu’on respecte beaucoup : ___",
"Un métier qu’on n’aimerait pas faire : ___",
"Un métier où on doit avoir du courage : ___",
"Un métier où on doit beaucoup parler : ___",
"Un métier où on doit beaucoup courir : ___",
"Un métier où on ne peut pas avoir peur du sang : ___",
"Un métier où on doit rester calme : ___",
"Un métier où on travaille souvent le week-end : ___",
"Un métier où on peut devenir célèbre : ___",
"Un métier où on peut gagner beaucoup d’argent : ___",
"Le meilleur sport à regarder à la télé : ___",
"Le sport le plus impressionnant : ___",
"Le sport le plus dangereux : ___",
"Le sport le plus difficile : ___",
"Le sport le plus ennuyeux à regarder : ___",
"Le sport le plus cher à pratiquer : ___",
"Le sport où les supporters sont les plus bruyants : ___",
"Le sport qu’on essaierait en vacances : ___",
"Le sport qu’on n’essaierait jamais : ___",
"Le sport où on se blesse facilement : ___",
"Un animal qui ferait un mauvais colocataire : ___",
"Un animal qui ferait un bon garde du corps : ___",
"Un animal qui paraît toujours énervé : ___",
"Un animal qui paraît toujours heureux : ___",
"Un animal qu’on aimerait voir de près : ___",
"Un animal qu’on ne voudrait pas voir de près : ___",
"Un animal qui ferait beaucoup de dégâts chez soi : ___",
"Un animal qu’on imagine avec une voix grave : ___",
"Un animal qu’on imagine avec une voix ridicule : ___",
"Un animal qu’on choisirait comme mascotte : ___",
"Le meilleur pays pour manger : ___",
"Le meilleur pays pour faire la fête : ___",
"Le meilleur pays pour la plage : ___",
"Le meilleur pays pour un road trip : ___",
"Le pays qu’on associe le plus au froid : ___",
"Le pays qu’on associe le plus au luxe : ___",
"Le pays qu’on associe le plus au football : ___",
"Le pays qu’on associe le plus au chocolat : ___",
"Une ville romantique : ___",
"Une ville où sortir le soir : ___",
"Une ville française pour un week-end : ___",
"Une ville où on n’aimerait pas conduire : ___",
"Une ville qu’on imagine très chère : ___",
"Une ville qu’on associe au cinéma : ___",
"Une destination de voyage de noces : ___",
"Un endroit où on aimerait se réveiller demain : ___",
"Un endroit où on ne voudrait pas être coincé : ___",
"Un endroit où on ne veut pas tomber en panne : ___",
"Le meilleur plat italien : ___",
"Le meilleur plat asiatique : ___",
"Le meilleur plat de fast-food : ___",
"Le meilleur dessert : ___",
"Le meilleur truc à manger à 2 h du matin : ___",
"Le meilleur truc à manger quand on est malade : ___",
"Le meilleur truc à manger quand il fait froid : ___",
"Le meilleur truc à manger quand il fait très chaud : ___",
"Le meilleur truc à mettre dans un sandwich : ___",
"Le pire truc à mettre sur une pizza : ___",
"Un aliment qui divise les gens : ___",
"Un aliment qu’on détestait enfant : ___",
"Un aliment qui sent mauvais mais qui est bon : ___",
"Un aliment qu’on mange trop facilement : ___",
"Un aliment qu’on ne commande pas au premier rendez-vous : ___",
"Une boisson de soirée : ___",
"Une boisson de petit-déjeuner : ___",
"Une boisson qu’on boit quand on est malade : ___",
"Une boisson qu’on associe aux vacances : ___",
"Une boisson qu’on commande quand on ne sait pas quoi prendre : ___",
"Une chanson parfaite pour un karaoké : ___",
"Une chanson qu’on connaît même sans l’aimer : ___",
"Une chanson qu’on entend trop en mariage : ___",
"Une chanson qu’on met pour se motiver : ___",
"Une chanson qu’on met pour faire la fête : ___",
"Un film qu’on peut revoir souvent : ___",
"Un film qu’on regarde à Noël : ___",
"Un film qui fait pleurer : ___",
"Un film qui fait peur : ___",
"Un film qu’on conseille à tout le monde : ___",
"Une série qu’on peut binge-watcher : ___",
"Une série qu’on regarde en couple : ___",
"Une série qui a duré trop longtemps : ___",
"Une série qu’on aimerait oublier pour la revoir : ___",
"Une série qu’on a l’impression que tout le monde a vue : ___",
"Un cadeau nul à recevoir : ___",
"Un cadeau qu’on n’ose pas revendre : ___",
"Un cadeau qu’on offre à quelqu’un qu’on connaît mal : ___",
"Un cadeau qu’on offre à un enfant de 10 ans : ___",
"Un cadeau qu’on offre à un ado : ___",
"Un cadeau qu’on offre à ses parents : ___",
"Un cadeau trop cher pour ce que c’est : ___",
"Un cadeau qui fait toujours plaisir : ___",
"Un cadeau qu’on peut fabriquer soi-même : ___",
"Un cadeau qu’on achète en catastrophe : ___",
"Une excuse pour annuler une soirée : ___",
"Une excuse pour ne pas aller au sport : ___",
"Une excuse pour ne pas répondre à un message : ___",
"Une excuse pour ne pas cuisiner : ___",
"Une excuse pour partir plus tôt du travail : ___",
"Une excuse pour ne pas prêter quelque chose : ___",
"Une excuse pour ne pas aider à déménager : ___",
"Une excuse pour ne pas sortir quand il pleut : ___",
"Une excuse pour être arrivé les mains vides : ___",
"Une excuse qu’on n’avale jamais : ___",
"Une chose qu’on fait dans une salle d’attente : ___",
"Une chose qu’on fait pendant une publicité : ___",
"Une chose qu’on fait quand personne ne regarde : ___",
"Une chose qu’on fait dans un ascenseur : ___",
"Une chose qu’on fait quand on ne trouve plus son téléphone : ___",
"Une chose qu’on fait en premier dans une chambre d’hôtel : ___",
"Une chose qu’on fait quand on reçoit une mauvaise nouvelle : ___",
"Une chose qu’on fait quand on ne comprend pas une blague : ___",
"Une chose qu’on fait avant une photo de groupe : ___",
"Une chose qu’on fait quand on a oublié un anniversaire : ___",
"Une chose qu’on ne veut pas entendre chez le dentiste : ___",
"Une chose qu’on ne veut pas entendre dans un avion : ___",
"Une chose qu’on ne veut pas entendre au restaurant : ___",
"Une chose qu’on ne veut pas entendre chez le garagiste : ___",
"Une chose qu’on ne veut pas entendre au moment de payer : ___",
"Une chose qu’on ne veut pas trouver dans son assiette : ___",
"Une chose qu’on ne veut pas trouver dans sa chaussure : ___",
"Une chose qu’on ne veut pas trouver dans sa voiture : ___",
"Une chose qu’on ne veut pas voir sur son relevé bancaire : ___",
"Une chose qu’on ne veut pas voir en ouvrant la porte : ___",
"Un truc qu’on achète en station-service : ___",
"Un truc qu’on ramène de vacances : ___",
"Un truc qu’on garde en souvenir : ___",
"Un truc qu’on collectionne facilement : ___",
"Un truc qu’on garde alors qu’on devrait le jeter : ___",
"Un truc qu’on a toujours trop dans les tiroirs : ___",
"Un truc qu’on n’a jamais quand on en a besoin : ___",
"Un truc qu’on prend en photo en vacances : ___",
"Un truc qu’on mange trop au buffet : ___",
"Un truc qu’on oublie de charger : ___"
];
